### ISSUE TITLE
Applying the framework to Prototypes

### ISSUE THREAD

**Issue by hamer101** [visinf/funnybirds-framework#1]
I've been analysing the workings of PI() interface function for ProtoPNet and its code implementation of [get_part_importance()](https://github.com/visinf/funnybirds-framework/blob/63464aceafdb16eb9e5a8179fa8801d2b482dd3c/explainers/explainer_wrapper.py#L71) method didn't quite answer my questions.

According to the article:
 _The importance score within the bounding box of a single prototype is the product of its similarity score and its class connection score. The importance score outside of the bounding box is zero. The final part importance is estimated by summing the importance scores of each prototype belonging to the class of interest._

With the core snippet being:
https://github.com/visinf/funnybirds-framework/blob/63464aceafdb16eb9e5a8179fa8801d2b482dd3c/explainers/explainer_wrapper.py#L78-L92

That, in my reasoning, would imply that the mentioned `attribution` variable would store an image composed of sum of bbox rectangles, whose contents are made up of products of prototypes' connection scores and similairty scores - with the value of the latter not being clear to me: is the bbox filled with its maximum similarity score, or granularly with the similarity scores heatmap?
Moreover, the `dilation1` seems still to be applied as for the attention and attribution map implementations: was it as well applied in the work?
And just fyi, it seems that the method's description got duplicated from `get_important_parts()` 😊

It would be wonderful if you could share your ProtoPNet implementation code :smile:

**Comment by robinhesse** [comment]
Hi,

In the implementation for the paper we simply use the maximum similarity score, as we found this to align better with, for example, Figure 5 of the ProtoPNet paper, where only bounding boxes are highlighted. However, since there is not a single correct way of implementing the interface functions (see paper), an implementation that is more granular is also valid, depending on the kind of explanation you want to provide.

I didn't quite get your question about dilation1 but the dilation is applied to the segmentation masks of the parts.

To keep this repository more clean we have decided to only include attribution maps here. The ProtoPNet code will soon be uploaded to [https://github.com/visinf/funnybirds](https://github.com/visinf/funnybirds) :) 

Best,
Robin
